### ISSUE TITLE
Unable to login to the extension

### ISSUE THREAD

**Issue by robertohuertasm** [atlassian/atlascode#35]
Hi, I've been using the extension so far, but a couple of days ago I noticed that I couldn't log in anymore:

<img width="1498" alt="image" src="https://github.com/user-attachments/assets/01d3e12f-c5df-44df-bb65-57feeba48fef" />

When I try to log in again, I go to the browser, see the scopes to authorize, accept, and then when I come back to VS Code, I see the image above.

This is what I see in the logs: 2024-12-16 11:26:42.132 [error] CancelError: Authentication for jiracloud has been cancelled.

Btw, I even installed the pre-release version but no luck. I've also checked the connected apps section in the account:

<img width="628" alt="image" src="https://github.com/user-attachments/assets/c6dd345f-1111-4b4f-91fa-3c8af07a557e" />

**Comment by robertohuertasm** [comment]
Ok, I removed the integration. Started the process again and it worked!

**Comment by inostia** [comment]
I had to uninstall the extension and re-install to fix this issue.
